name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  lint:
      name: Node ${{ matrix.node }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          node: [12]
          os: [ubuntu-latest]

      steps:
        - name: Clone repository
          uses: actions/checkout@v1

        - name: Set Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}

        - run: node --version
        - run: npm --version

        - name: Install npm dependencies
          run: npm install

        - name: Run lint
          run: npm run lint
  test:
      name: Node ${{ matrix.node }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          node: [6, 8, 10, 12, 14]
          os: [ubuntu-latest, windows-latest]

      steps:
        - name: Clone repository
          uses: actions/checkout@v1

        - name: Set Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}

        - run: node --version
        - run: npm --version

        - name: Install npm dependencies
          run: npm install

        - name: Run tests
          run: npm run mocha
